### PR TITLE
Mirror the grainc usage for tests

### PR DESCRIPTION
**Pull request by phated**
Just trying to cleanup the things @ospencer had to do to make my PR work.

### CODE REVIEW

**Comment by phated** [comment]
Not sure why travis didn't run?

**Comment by phated** [comment]
https://travis-ci.org/github/grain-lang/grain/builds/665361311

**Comment by ospencer** [comment]
https://travis-ci.org/github/grain-lang/grain/builds/665382870?utm_source=github_status&utm_medium=notification

**Comment by ospencer** [comment]
Much better.

**Pull request merged**
