### PR TITLE
feat(compiler)!: Change `->` to `=>` in type signatures

### PR DESCRIPTION
**Pull request by alex-snezhko**
Closes #1179 (supersedes)

### CODE REVIEW

**Review by spotandjake — APPROVED** [review]
This looks good to me. 

I don't fully understand the code in the lever hack that checks the data types but what I did understand looks good.

**Review by ospencer — APPROVED** [review]
Fantastic work here!

**Review by marcusroberts — APPROVED** [review]
If Oscar's happy with the parsing, this looks great.

One question, can we use the formatter or provide a utility to help people bulk change their code to the new style?

**Review by peblair — COMMENTED** [review]
Two comments:
1. I would love to see some stress tests/weird cases which should not parse (`let f = (foo, bar) => Number`) in the test suite
2. Extremely minor concern: just want to double-check other Core Team members (cc @ospencer and @phated especially) are cool with this possibly introducing some potential confusion for new users (e.g. `let lexer : (stream) => List<Token>` might look to a new user like `stream` is supposed to be the name of the function argument and not a placeholder type).

**Comment by spotandjake** [comment]
> 2. Extremely minor concern: just want to double-check other Core Team members (cc @ospencer and @phated especially) are cool with this possibly introducing some potential confusion for new users (e.g. `let lexer : (stream) => List<Token>` might look to a new user like `stream` is supposed to be the name of the function argument and not a placeholder type).

I feel like the issue of the confusion was already there before the arrow change.

**Comment by peblair** [comment]
> I feel like the issue of the confusion was already there before the arrow change.

Yes, true, but the `->` syntax made it a bit more clear when reading quickly that one was looking at a type, not a function definition. Maybe I am wording this scenario wrong, but I am just envisioning some potential weird interaction with the unified `=>` syntax and placeholder type names

**Comment by alex-snezhko** [comment]
@peblair I added some parsing tests to `types.re`; are those the sort of cases you had in mind?

**Review by phated — APPROVED** [review]

**Comment by phated** [comment]
Going to merge this, we can always add more tests later 🎉

**Pull request merged**
