### PR TITLE
feat(compiler): Name globals in wasm output

### PR DESCRIPTION
**Pull request by ospencer**
This is more code cleanup than anything else, largely from old logic we needed back before we used Binaryen. Additionally, it'll make it easier for us to debug what's going in in the wasm output since we'll actually see the names of globals getting assigned rather than just `global_0` etc.

### CODE REVIEW

**Review by peblair — APPROVED** [review]
❤️

**Review by marcusroberts — APPROVED** [review]
I can only say LGTM!

**Review by jozanza — APPROVED** [review]
🔥

**Review by phated — APPROVED** [review]
Love the code cleanup 🎉

**Pull request merged**
