### PR TITLE
fix(compiler): Type aliasing in `use` statements

### LINKED ISSUE #1869: Lang: Re-providing aliased types fails
Attempting to re-provide a type from one module after aliasing it with a `use` alias causes a compilation failure. Example that causes a failure:
```
//a.gr
module A
provide enum T {
  Val
}

// b.gr
module B
include "./a"
from A use { type T as AliasedT }
provide { type AliasedT }
```

### PR DESCRIPTION
**Pull request by alex-snezhko**
Closes #1869

### CODE REVIEW

**Review by spotandjake — APPROVED** [review]
Looks great 👍

**Review by ospencer — COMMENTED** [review]
Could you add tests where you annotate using the alias?

**Review by peblair — APPROVED** [review]
LGTM (with the test that @ospencer requested)

**Comment by alex-snezhko** [comment]
Added a test with annotation

**Review by ospencer — APPROVED** [review]
Excellent, great work!

**Pull request merged**
