### PR TITLE
feat: Export number runtime functions as operators & deprecate old identifiers

### LINKED ISSUE #546: Runtime: Export number function names as the operator
We currently export the functions as names like `numberPlus` (which should have been `numberAdd`, but I digress) but it should instead just be exported as `(+)`.

### PR DESCRIPTION
**Pull request by jozanza**
Closes #546

### CODE REVIEW

**Comment by ospencer** [comment]
@jozanza Looks great! Since you changed some of the functions to say `Add` instead of `Plus`, could you also change `Minus` to `Sub`? 🙏

**Comment by jozanza** [comment]
You got it

**Review by phated — CHANGES_REQUESTED** [review]
This is breaking so I'm putting a pause on it until 0.4.0 work begins to land

**Comment by jozanza** [comment]
I just pushed another commit that continues to export the deprecated methods, similar to #635

**Review by phated — APPROVED** [review]
I think this looks solid to merge with the deprecation strategy and messaging!

**Review by ospencer — APPROVED** [review]

**Pull request merged**
