### PR TITLE
feat: Implement Grain array methods in Grain instead of the compiler

### PR DESCRIPTION
**Pull request by ospencer**
I left `ArrayLength` in the compiler since it's used by `match`.

### CODE REVIEW

**Review by ng-marcus — APPROVED** [review]
I'm not 100% qualified to approve this, but LGTM and great to see Grain implementing Grain!

**Review by marcusroberts — APPROVED** [review]
And now as the real me (sorry!)

I'm not 100% qualified to approve this, but LGTM and great to see Grain implementing Grain!

**Review by peblair — APPROVED** [review]
These code changes look good!

**Comment by phated** [comment]
Something I'd like to know is how this will affect array pattern matching, specifically how we'll implement recursion with them in the future.

**Comment by ospencer** [comment]
@phated I'm not quite sure what you mean. Can you give me an example?

**Comment by phated** [comment]
@ospencer I'm afk, I just realized I needed to say something now that there were 2 approvals. We have an open issue about it, can you search for it?

**Comment by ospencer** [comment]
@phated Yes, it's #490. No effect whatsoever! This PR is essentially just pulling some stdlib code that was baked into the compiler out since we didn't have the ability to do it this way when it was originally written.

**Pull request merged**
