### PR TITLE
ReasonML formatting

### PR DESCRIPTION
**Pull request by phated**
This formats the Reason code and then adds a format checking phase to our CI.

As you can probably tell, Reason has some issues with block comments and we should probably switch them to line comments (which it seems to handle much more elegantly).

Not sure if this is enough to satisfy all of #218 - Thoughts?

I'll push up a sample of the lint failing once it passes just as an example.

### CODE REVIEW

**Comment by phated** [comment]
I pushed some incorrectly formatted code to another branch. This build: https://github.com/grain-lang/grain/actions/runs/167901512 should fail shortly with a formatting problem.

**Comment by ospencer** [comment]
Do you think we could make the linting a separate CI job? That'd make it more obvious that the linting was the reason it failed.

**Comment by phated** [comment]
@ospencer then we'd have 2 builds racing to build the compiler. Unfortunately, everything needs to be built before esy can execute the dune commands.

**Comment by ospencer** [comment]
That's fair. Thoughts on making the format command just be the default build command?

**Comment by phated** [comment]
I also tried that but the command exits with non-zero if it formats (even with auto-promotion) so I didn't want to do that because building the compiler shouldn't fail for just formatting problems.

**Pull request merged**
