### PR TITLE
feat(stdlib)!: Add `print` suffix default argument

### PR DESCRIPTION
**Pull request by alex-snezhko**
Adds `suffix` argument to `print` (default `"\n"`). Enables printing without newline for instance
```
print(123, suffix="")
```

### CODE REVIEW

**Review by spotandjake — APPROVED** [review]
Looks good.

**Review by peblair — APPROVED** [review]

**Comment by alex-snezhko** [comment]
Updated to use new default argument graindoc syntax

**Review by spotandjake — APPROVED** [review]
This looks great, lets get this merged

**Comment by ospencer** [comment]
I don't love the param name `end`. Maybe something like `lineEnding`?

**Comment by alex-snezhko** [comment]
Made in `lineEnding`

**Comment by ospencer** [comment]
Looks like you forgot to update the tests.

**Comment by alex-snezhko** [comment]
Updated

**Comment by ospencer** [comment]
Alright, don't be annoyed with me: I thought about it and I think `lineEnding` might actually be a bad name since it could imply that it's going to change EOL characters in the output. I still don't really like `end`, but I haven't thought of anything better.

**Comment by phated** [comment]
`suffix`

**Comment by ospencer** [comment]
`suffix` is better.

**Comment by alex-snezhko** [comment]
Made it `suffix`

**Review by phated — APPROVED** [review]

**Pull request merged**
