### PR TITLE
Chore(stdlib): Add Since Propertys to Result GrainDoc

### PR DESCRIPTION
**Pull request by spotandjake**
Add Since Properties to Result GrainDoc.

related: #702.

### CODE REVIEW

**Comment by phated** [comment]
@spotandjake it looks like there might have been a git issue here. Can you cherry-pick or rebase these changes on main?

**Comment by spotandjake** [comment]
> @spotandjake it looks like there might have been a git issue here. Can you cherry-pick or rebase these changes on main?

Idk what happend lol but i think it is fixed now.

**Review by phated — APPROVED** [review]
Looks great! Thanks!

**Review by ospencer — APPROVED** [review]
Amazing, thank you!!

**Pull request merged**
