### PR TITLE
chore!: Require node version >=18.15 for WASI support

### PR DESCRIPTION
**Pull request by spotandjake**
This pr switches grain to use node v18 over node v16.

This pretty much does the same stuff as #1092.
except the docker workflows have been added so we also update those files.

Closes: #1597

### CODE REVIEW

**Comment by phated** [comment]
@spotandjake there's no reason for this because, like I mentioned on the community meeting, we need to wait for node 19 to include the WASI updates and then upgrade to that minimum.

**Comment by phated** [comment]
Marked as draft and updated the linked issue.

**Comment by phated** [comment]
Node has finally release 19.6 so I'm working to get this updated and passing. This might change again before 0.6 releases because node could backport the WASI patch and/or they might make WASI stable on a newer version of 19.x but we want to land a working version of WASI to unblock some other work.

**Comment by phated** [comment]
Blocked on pkg accepting my patch. I'll ping them again

**Comment by phated** [comment]
They backported the wasi stuff to 18.15 so I'm setting that as our minimum

**Comment by phated** [comment]
We're switching to my pkg fork until upstream publishes the new stuff.

**Review by ospencer — APPROVED** [review]

**Pull request merged**
