### PR TITLE
chore(stdlib): Regenerate GrainDoc For stdlib.

### PR DESCRIPTION
**Pull request by spotandjake**
The GrainDoc on the regex libary was out of date.

### CODE REVIEW

**Comment by phated** [comment]
@spotandjake excellent! Would you want to regenerate docs for each stdlib that exists? We probably have other lingering `next` tags that I'd like to get cleaned up.

**Comment by spotandjake** [comment]
Sure, Probably gonna want to add this to the graindoc test suite whenever that gets running lol

**Comment by phated** [comment]
> Probably gonna want to add this to the graindoc test suite whenever that gets running

It's an open item. Needs other stuff first.

**Comment by spotandjake** [comment]
> > Probably gonna want to add this to the graindoc test suite whenever that gets running
> 
> It's an open item. Needs other stuff first.

👍 also regenerated the rest of the libs docs. i think regex was the only one that really had `next` floating arround

**Review by phated — APPROVED** [review]
Looks good! Thanks!

**Review by ospencer — APPROVED** [review]
Excellent!

**Pull request merged**
