### PR TITLE
Update Binaryen usage to match latest bindings

### PR DESCRIPTION
**Pull request by jozanza**
This should fix `Binaryen`-related type errors, after [this PR](https://github.com/grain-lang/binaryen.ml/pull/102) gets merged, and we update the `@grain/binaryen.ml` dependency

### CODE REVIEW

**Comment by phated** [comment]
These are all the changes batched up in https://github.com/grain-lang/binaryen.ml/pull/99 (that will result in binaryen.ml v0.10.0). Both @jozanza and I did a bunch of the API refactor, so I'd like to get approvals from @ospencer, @peblair and @marcusroberts

**Review by ospencer — APPROVED** [review]
Looking good! Thanks @jozanza and @phated!

**Review by peblair — APPROVED** [review]
Looks good. Thanks!

**Comment by ng-marcus** [comment]
This branch compiles cleanly and runs on Mint Linux, but the compiler version reported is slightly behind:

marcus@marcus-Virtual-Machine:~/Grain/grain$ ~/.yarn/bin/grain --version
Grain cli 0.3.0
Grain compiler 0.3.0

**Comment by ng-marcus** [comment]
Builds and runs on Mint 19, Ubuntu 18 and Ubuntu 20, so I'm happy

**Review by ng-marcus — APPROVED** [review]

**Pull request merged**
