### PR TITLE
chore: Update inline docs for sys/file

### LINKED ISSUE #576: Stdlib: Verify inline doc comments from sys/file.gr

### PR DESCRIPTION
**Pull request by ospencer**
Closes #576 

See also: https://github.com/grain-lang/grain-lang.org/pull/166

### CODE REVIEW

**Comment by phated** [comment]
@ospencer I just pushed my consistency updates here. Please take a look when you have the chance.

**Comment by ospencer** [comment]
Wow, so many!

**Comment by ospencer** [comment]
@phated looks great! What should be our plan be for the docs on the website?

**Comment by phated** [comment]
I was just going to copy them over from the file. I'll get this merged now and that updated after triaging the issue tracker.

**Pull request merged**
