### PR TITLE
fix(stdlib): String.writeUtf8CodePoint should write 3 bytes for code point 0xFFFF.

### PR DESCRIPTION
**Pull request by cician**

### CODE REVIEW

**Review by peblair — APPROVED** [review]
Good catch!

**Review by phated — APPROVED** [review]
I don't know code points, but I trust @peblair's approval. 👍

**Comment by phated** [comment]
Oh, is there a test we can add for this to avoid regression?

**Comment by peblair** [comment]
For reference: http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=FFFF&mode=hex

**Review by ospencer — APPROVED** [review]
Thanks, and sorry for the delay!

**Comment by cician** [comment]
No problem and you're welcome.

**Pull request merged**
