### PR TITLE
fix(compiler): Allow reproviding from submodules

### LINKED ISSUE #1872: Lang: re-providing from submodules fails
Re-providing a value from a submodule in the parent module fails unexpectedly; an example that fails to compile:
```
module A

module B {
  provide let x = "asdf"
}
from B use *
provide { x }

// compilation error: Failure("Impossible: import path not found B.x")
```
However, if `B` were instead extracted into a separate file the issue does not occur:
```
// b.gr
module B
provide let x = "asdf"

// a.gr
module A
include "./b"
from B use *
provide { x }

// compiles fine
```

### LINKED ISSUE #1885: Lang: re-providing modules fails
```
// a.gr
module A
provide module Inner {
  // ...
}

// b.gr
module B
include "./a"
from A use { module Inner }
provide { module Inner }
```
The above code fails to compile with the error:
```
[wasm-validator error in module] unexpected false: module global exports must be found, on 
m_1119
/home/avs/projects/grain-pr/cli/bin/grainc.exe: internal error, uncaught exception:
                                                WASM Runner Exception in compiler/b.gr: WARNING: Invalid module
                                                
                                                Raised at [...]
```

### PR DESCRIPTION
**Pull request by alex-snezhko**
Closes #1872 
Closes #1885

### CODE REVIEW

**Review by ospencer — APPROVED** [review]
Good catch here!

**Comment by alex-snezhko** [comment]
I discovered a fix to #1885 as well and added it to this PR

**Review by spotandjake — APPROVED** [review]
Looks good to me.

**Review by peblair — APPROVED** [review]
Nice!

**Review by phated — APPROVED** [review]
This looks great. Thanks @alex-snezhko 🎉

**Pull request merged**
