### PR TITLE
fix(lsp): Add test harness, update named arg code action title, fix code action trigger points, do not print LSP warnings

### PR DESCRIPTION
**Pull request by alex-snezhko**
* Add LSP test harness, test most major LSP functionality
* Make some improvements to LSP behavior according to expected behavior in tests

### CODE REVIEW

**Review by ospencer — COMMENTED** [review]
Pretty cool! Can you specify the behavior improvements in the PR title?

**Comment by alex-snezhko** [comment]
@ospencer updated

**Comment by ospencer** [comment]
Looks like you've got some line ending issues on Windows.

**Review by marcusroberts — APPROVED** [review]
It's great to get a test harness in place like this.   

Other fixes look good too!

**Review by spotandjake — COMMENTED** [review]
This looks great, I am wondering if we should allow for the option of a `snapshotRunner` for some of these tests. 

This also closes #1798

**Comment by alex-snezhko** [comment]
@ospencer I fixed the Windows issues

**Review by ospencer — APPROVED** [review]

**Pull request merged**
