### PR TITLE
refactor: extract header & trailer from parser.dyp

### PR DESCRIPTION
**Pull request by phated**
This extracts the header and trailer code from the `parser.dyp` file and puts it into a `parser_extra.re` file. It also converts the OCaml code to ReasonML and documents why they are externalized.

I only had to change the `parse_program` method to include dypgen's `program` value in the function signature and then it is partially applied at the bottom of the `parser.dyp` file.

### CODE REVIEW

**Comment by phated** [comment]
FWIW, I could be convinced to change the filename to `parser_header` now that everything is included into the header

**Review by ospencer — CHANGES_REQUESTED** [review]
Looks great! I would prefer `parser_header` 🙂

**Comment by phated** [comment]
Rename complete!

**Review by ospencer — APPROVED** [review]
Woohoo!

**Pull request merged**
