### PR TITLE
fix(stdlib): Fix memory issue in list printing

### LINKED ISSUE #905: DecRefError caused by print
The following program halts with DecRefError exception (on latest git main).

With some magic print debugging I see the DecRefError happening on an instance of string "JSONNull".
Also if I remove the two lines containing JSONNull, then instead of a DecRefError I get an infinite loop in Malloc.free.

```grain
enum JSON {
  JSONNull,
  JSONBoolean(Bool),
  JSONNumber(Number),
  JSONString(String),
  JSONArray(List<JSON>),
  JSONObject(List<(String,JSON)>),
}

print(JSONArray(
  [
    JSONNull,
    JSONBoolean(true),
    JSONBoolean(false),
    JSONNumber(2),
    JSONNumber(-2),
    JSONNumber(0),
    JSONNumber(-0),
    JSONNumber(1152921504606846976),
    JSONNumber(1E2),
    JSONNumber(1E-2),
    JSONNumber(1/2),
    JSONArray([JSONNull]),
    JSONArray([JSONNumber(1), JSONNumber(2), JSONNumber(3)]),
    JSONObject([("pinco", JSONString("pallino")), ("pippo", JSONNumber(4543))]),
    JSONObject([("just", JSONString("one"))]),
  ],
))
```

### PR DESCRIPTION
**Pull request by ospencer**
Fixes #905

### CODE REVIEW

**Review by peblair — APPROVED** [review]
🙃

**Comment by peblair** [comment]
@ospencer It's `fix(stdlib)`, no?

**Comment by ospencer** [comment]
Yeah, my bad.

**Review by marcusroberts — APPROVED** [review]
That's an amazing bug to track down, I read straight over the problem, then BAM

**Pull request merged**
