### PR TITLE
chore(compiler)!: Remove decRefIgnoreZeros

### PR DESCRIPTION
**Pull request by ospencer**
I called this breaking because I removed an export from the runtime. I think it's fine to send this with 0.5.0.

### CODE REVIEW

**Review by peblair — APPROVED** [review]
LGTM

**Comment by phated** [comment]
@ospencer now that #768 has been merged, can you also update the contributor docs about decRefIgnoreZeros as a part of this PR?

**Comment by ospencer** [comment]
@phated All up to date.

**Review by phated — APPROVED** [review]
Awesome! Thanks for getting that other cleanup in. 🎉

**Review by marcusroberts — APPROVED** [review]
LGTM too!

**Pull request merged**
