### PR TITLE
fix(grainfmt): Handle source files with no code, only comments

### PR DESCRIPTION
**Pull request by marcusroberts**
Still format the comments correctly.

### CODE REVIEW

**Review by phated — CHANGES_REQUESTED** [review]
I'd like to see some tests

**Comment by marcusroberts** [comment]
@phated  added some simple tests

**Review by phated — APPROVED** [review]
Sweet! Thanks for adding the tests too 🙇

**Review by ospencer — APPROVED** [review]
Beautiful!

**Pull request merged**
