### PR TITLE
feat(compiler): Remove Pervasives' dependency on toString when types are elided

### PR DESCRIPTION
**Pull request by ospencer**
This PR removes the forced dependency on `toString` when types are elided at runtime. If there's no type information, all of the code that comes with `toString` is of no help. This reduces module sizes for programs that don't otherwise depend on toString.

Works towards #1029

### CODE REVIEW

**Comment by peblair** [comment]
Is it expected that there are no major snapshot changes? I can believe it, but I want to double-check

**Comment by ospencer** [comment]
Nah, no snapshot changes. This would be a change on the snapshot of Pervasives itself, if we had one.

**Review by phated — APPROVED** [review]
LGTM

**Review by peblair — APPROVED** [review]
Ditto 👍

**Pull request merged**
