### PR TITLE
chore: Clean up function tables

### PR DESCRIPTION
**Pull request by ospencer**
We were putting way more than we needed to in our function tables, so this PR cleans that up. It also makes processing of function names a bit cleaner.

### CODE REVIEW

**Comment by peblair** [comment]
@ospencer Can you elaborate a little more on what is being removed here? It's not immediately obvious to me based on a read of the diff.

**Comment by ospencer** [comment]
@peblair Previously, we put _all_ functions that appeared in a module in the function table. This includes function imports, functions defined by the module, `_start`, and other auxiliary functions. Really, all that needs to go in the table are the functions defined by the module that a closure will have a pointer to. All Grain function imports are already in the function table because they were put there by the module they were defined in. External functions don't need to be placed in the table because the version of the function that Grain creates a closure for is put in the table.

This is why we were seeing a sort of ballooning of our function table size, since every module duplicated the tables 🤦. Now the table size is equivalent to the number of functions you defined in your module.

The other huge benefit here is for Binaryen optimizations—since we put all imports in the function table, Binaryen couldn't remove unused imports 😭.

**Comment by ospencer** [comment]
(Pending #196 of course.)

**Review by peblair — APPROVED** [review]
Looks like this will help a lot with compilation efficiency!

**Pull request merged**
