### PR TITLE
feat(stdlib): Int32/64 clz, ctz, popcnt, rotl, rotr, eq, ne, eqz

### LINKED ISSUE #804: Int32 and Int64 Popcnt
Please add as many as possible bit operations that available on wasm. such as popcnt. and rotl rotr... etc.
They are very good in encryption operation and more.
Thanks...

### PR DESCRIPTION
**Pull request by ospencer**
Closes #804

### CODE REVIEW

**Review by phated — APPROVED** [review]
Seems straight forward! One question though - do we want `eq` and `ne` to be exported as that or as the `==` and `!=` operators? I forget where we landed on all that.

**Review by marcusroberts — APPROVED** [review]

**Comment by ospencer** [comment]
@phated I think we wanted the infix operators for the things that would eventually get exported from Pervasives, but for these, the alphabetical names are easier to use when importing (and to force you to be explicit if you want to shadow the operators).

**Review by peblair — CHANGES_REQUESTED** [review]
Needs GC instructions now that #803 has landed

**Review by peblair — APPROVED** [review]
LGTM 👏 🚀

**Pull request merged**
