### PR TITLE
add Array.unzip and tests for zip and unzip

### PR DESCRIPTION
**Pull request by MihailITPlace**
Hello. I tried to solve the problem from issue #694. This PR adds Array.unzip function and some tests for Array.zip and Array.unzip.

### CODE REVIEW

**Review by peblair — APPROVED** [review]
Hello, thank you for the contribution, and thank you for adding the tests for `Array.zip`! This implementation looks good. I am satisfied with it, but someone else from the core team should take a look too and decide if we should optimize it a bit more. Thanks again!

**Review by ospencer — COMMENTED** [review]
I think this implementation is fine. The more performant one is far more complicated, and I don't think it's all that worth it. We can optimize it later if we really want to.

Let's not merge this until Regex is landed though, so we don't have too much in that PR. Thanks @MihailITPlace!

**Comment by MihailITPlace** [comment]
Thank you for the opportunity to contribute!

**Comment by peblair** [comment]
Hello again, @MihailITPlace! We've broken up the regular expression PR into a few separate ones, so the `Array.zip` functionality has now been merged into `main`. Would you be able to rebase this branch onto `origin/main` (and update the PR to point to `main`)? With that, I think we'd be ready to merge this in. Thank you!

**Comment by MihailITPlace** [comment]
Hello, @peblair. I tried rebase onto main and changed the target branch in the PR. But now there are new commits in PR that shouldn't be. Could you tell me what I did wrong?

**Comment by peblair** [comment]
@MihailITPlace No worries, I can fix the Git history for you. Can you give us (or me) write access to the branch?

**Comment by MihailITPlace** [comment]
@peblair Of course, I sent an invitation to collaborate

**Comment by peblair** [comment]
@MihailITPlace Perfect, it should be fixed now. You can fix your local state with this (assuming your remote is named `mihail`; you can change it to `origin` or whatever else you have it as):
```
$ git checkout feat/array-unzip
$ git fetch
$ git reset --hard mihail/feat/array-unzip
```

**Comment by peblair** [comment]
For reference, these were the commands I used to fix it:
```
$ git checkout feat/array-unzip
$ git cherry-pick ad7f1fe3d3e91ba51923b34cd576733769af90cc
< fix up conflicts >
$ git cherry-pick --continue
$ git push --force-with-lease
```
Now, that set of commands was different than usual, since I was fixing up the broken history. Typically, I would do the following to rebase the whole branch:
```
$ git fetch
$ git rebase origin/main
< fix up conflicts >
$ git rebase --continue
$ git push --force-with-lease
```

**Comment by MihailITPlace** [comment]
@peblair, thank you very much! Now I just have to wait for approval from another team member, right?

**Comment by peblair** [comment]
@MihailITPlace sure thing! Yes, I think that all that's left is for another approval to come along, and then we can merge this in. Hopefully that means nothing left on your end! 🙂

**Review by ospencer — APPROVED** [review]
Perfect, thank you @MihailITPlace!

**Comment by marcusroberts** [comment]
Hi, thanks for the contribution @MihailITPlace! 

The documentation for Array.zip says it should throw an error if the arrays are of different lengths.  @peblair is that something we (should) test for?

**Comment by phated** [comment]
> The documentation for Array.zip says it should throw an error if the arrays are of different lengths. @peblair is that something we (should) test for?

@marcusroberts Unfortunately we can't yet test for `fail` throws because there is no way to catch exceptions (we are waiting on the wasm spec for it).

**Review by phated — APPROVED** [review]
So awesome!

**Pull request merged**
