### PR TITLE
feat(stdlib): Implement PriorityQueue.fromArray and ImmutablePriorityQueue.fromArray

### PR DESCRIPTION
**Pull request by alex-snezhko**
Minor improvements to `PriorityQueue` & `ImmutablePriorityQueue`
- Implemented `fromArray` on both modules for parity with other data structures
- Implemented more efficient algorithm for constructing a mutable PQ from a list/array, with worst-case O(n) asymptotic running time up from O(nlog(n))

### CODE REVIEW

**Comment by phated** [comment]
This builds upon #1414 right? Do we want to change the base branch?

**Comment by alex-snezhko** [comment]
Yeah my mistake, I realized right after submitting this PR that I branched off the wrong base branch, I'll update in a sec

**Review by ospencer — APPROVED** [review]
Looks great!

**Review by phated — APPROVED** [review]
Looks great! Thanks 🙇

**Pull request merged**
