### PR TITLE
Add JS FFI import support

### PR DESCRIPTION
**Pull request by z0w0**
This adds a `import foreign js funcName : Args -> Result from 'module'` syntax for
importing and calling JS functions directly from Grain per #39. Any modules must be declared
when instantiating the runtime using a new `.addJSImports` method like so:

```js
runner.addJSImports({
  moduleName: {
    someFunc: () => { console.log('this can do anything like a plain old JS function'); }
  }
});
```

The runtime then wraps those JS function imports so that Grain argument values are converted into JS argument values and JS return values are converted to Grain return values. Under the hood, JS imports are outputted just like WASM imports in the compiled WASM, except JS imports implicitly live under the "js/" module name prefix. This module name prefix is then populated using the aforementioned `.addJSImports` method.

At the moment there are no pre-defined JS imports within the runtime, but over at [grain-loader](https://github.com/z0w0/grain-loader) I've added support for passing in JS imports when calling a compiled Grain program, for e.g.

```
import foreign js alert : String -> Void from 'window'

alert("Hello world");
```

Can be compiled and used in a Webpack bundle like so:

```js
const hello = require('./hello.gr');

hello({
  window: {
    alert: window.alert
  }
});
```

We can add some pre-defined JS imports to the runtime here in the future and possibly allow additional ones to be passed into `grain run` since it's running on Node.js.

### CODE REVIEW

**Comment by ospencer** [comment]
Hey Zack, awesome that you took this on! The code is good and the API is exactly what we wanted. We hadn't done this yet since we don't have well-defined semantics for the conversion functions and they're currently only used internally. Since this exposes them (albeit indirectly) to users, we have to hammer down what all of the semantics are supposed to be and get them documented.

If you're willing to work with us to get that done, we can get this over the line 🙏

**Comment by z0w0** [comment]
No problem, I'm happy to improve and document the conversion functions as part of this PR. It's definitely a blocker at the moment anyway since anything other than primitive types will throw a runtime error right now. Let me know how you would like to proceed with standardising the semantics.

**Comment by ospencer** [comment]
@z0w0 Sorry we haven't gotten back to this yet! I wanted to land #414 and get some reference types in so we can use abstract types with this. I've been a little bit stuck on an annoying bug with it for a bit. Hopefully I'll have some updates for you soon!

**Comment by ospencer** [comment]
@z0w0 we swapped our default branch from master -> main, so I got this rebased and updated in #549. I just need to figure out how to get you commit access on that branch 😅 

Closing this since the histories are unrelated.

**Pull request closed without merging**
