### PR TITLE
fix(stdlib): Fix Char.code memory issue

### LINKED ISSUE #927: Infinite loop inside malloc.free
The below program causes an infinite loop inside `malloc.free`. It finishes without issues if executed with `--no-gc`.

I tried to narrow it down further, but gave up. Slight changes like the following make it **not** hang anymore:
- Changing the chars to simple ASCII values like 'a' and 'b'.
- Moving the if statement to the end of the loop.
- Changing the loop to `while(true)` or `for(;;)`.
- Not calling `Char.code`. Though I doubt it's got much to do with Char.code function itself, even if it's not fully conformant with the new convention for manual memory management.

``` grain
import Char from "char"

let chars = [> '\u{1F3F4}', '\u{E0067}' ]
let mut charPosition = 0
let len = 2
let mut done = false

while (!done) {
	if (charPosition >= len) {
		break
	}
	
	Char.code(chars[charPosition])
	charPosition = charPosition + 1
}
```

### PR DESCRIPTION
**Pull request by ospencer**
Fixes #927

### CODE REVIEW

**Review by phated — APPROVED** [review]
🐞 @cician puts them up and @ospencer knocks them down 🔨

**Review by marcusroberts — APPROVED** [review]
!!

**Comment by cician** [comment]
> lady_beetle @cician puts them up and @ospencer knocks them down hammer

I thought the Wales flag emoji was cursed, but it was just bugs.  🐛 🦋 🪲🏴󠁧󠁢󠁷󠁬󠁳󠁿🐞🦗🪳

**Comment by cician** [comment]
Since we're at it. Shouldn't it also decRef itself and the passed Char?

**Comment by ospencer** [comment]
You are absolutely right!

**Comment by ospencer** [comment]
I'll resolve those in a separate PR, though. Looks like this module was missed.

**Pull request merged**
